// flow-typed signature: 7d8888724bbb539b44461b22662f9c8f
// flow-typed version: <<STUB>>/node-tcp-proxy_v^0.0.24/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-tcp-proxy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-tcp-proxy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-tcp-proxy/examples/logger' {
  declare module.exports: any;
}

declare module 'node-tcp-proxy/tcp-proxy-cli' {
  declare module.exports: any;
}

declare module 'node-tcp-proxy/tcp-proxy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-tcp-proxy/examples/logger/index' {
  declare module.exports: $Exports<'node-tcp-proxy/examples/logger'>;
}
declare module 'node-tcp-proxy/examples/logger/index.js' {
  declare module.exports: $Exports<'node-tcp-proxy/examples/logger'>;
}
declare module 'node-tcp-proxy/index' {
  declare module.exports: $Exports<'node-tcp-proxy'>;
}
declare module 'node-tcp-proxy/index.js' {
  declare module.exports: $Exports<'node-tcp-proxy'>;
}
declare module 'node-tcp-proxy/tcp-proxy-cli.js' {
  declare module.exports: $Exports<'node-tcp-proxy/tcp-proxy-cli'>;
}
declare module 'node-tcp-proxy/tcp-proxy.js' {
  declare module.exports: $Exports<'node-tcp-proxy/tcp-proxy'>;
}
